---
downloads: ~/Downloads/.ansible-downloads

homebrew_installed_packages:
  - go

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - google-chrome
  - karabiner-elements
  - skype
  - visual-studio-code
  - vlc
  - zoom

configure_terminal: true

configure_dock: true
dockitems_remove:
  - 'App Store'
  - 'System Settings'
  - Contacts
  - FaceTime
  - Keynote
  - Mail
  - Maps
  - Messages
  - Music
  - Numbers
  - Pages
  - Photos
  - Podcasts
  - TV

dockitems_persist:
  - name: 'Google Chrome'
    path: '/Applications/Google Chrome.app'
  - name: 'Visual Studio Code'
    path: '/Applications/Visual Studio Code.app'

