---
- name: Create a download directory for Martian Mono font
  file:
    path: "{{ downloads }}/martian-mono"
    state: directory

- name: Download Martian Mono font
  ansible.builtin.unarchive:
    src: https://github.com/evilmartians/mono/releases/download/v1.0.0/martian-mono-1.0.0-ttf.zip
    dest: "{{ downloads }}/martian-mono"
    remote_src: yes

- name: Install Martian Mono fonts
  shell: find {{ downloads }}/martian-mono -name "*.ttf" -exec ditto {} /Library/Fonts \;
  args:
    executable: /bin/bash
    chdir: "{{ downloads }}/martian-mono"

- name: Delete the download directory for Martian Mono font
  file:
    path: "{{ downloads }}/martian-mono"
    state: absent
